name: Docker Image CI

on: [workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Run Tests
      run: |
        echo --Running Test cases-----
        docker-compose -f "docker-compose.yml" up
        
    - name : Stop containers
      if: ${{always()}} 
      run: docker-compose -f "docker-compose.yml" down
